/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import comunicacion.Cliente;
import comunicacion.Servidor;
import hilos.HiloDisco;
import hilos.HiloProcesador;
import hilos.HiloRam;
import java.io.BufferedReader;
import java.io.InputStreamReader;

/**
 *
 * @author root
 */
public class ClienteVista extends javax.swing.JFrame {

    int xMouse=0;
    int yMouse=0;
    int contador=0;
    Cliente c;
    HiloRam hram;
    HiloDisco hdisco;
    HiloProcesador hprocesador;
    
    public ClienteVista() {
        initComponents();
        c = new Cliente("10.0.2.15",2704);
        if(!c.conectar()){
            comando.setText("Error al conectarse con el server");
            comando.setEditable(false);
        }
        hram = new HiloRam(porcentajememoria,c);
        hram.start();
        hdisco = new HiloDisco(porcentajedisco,c);
        hdisco.start();
        hprocesador = new HiloProcesador(porcentajeprocesador,c);
        hprocesador.start();
        //new Servidor();
        
        /*try{
            for(int i=0; i<100; i++){
                porcentajememoria.setText(String.valueOf(i));
                Thread.sleep(3*1000);
            }
        }catch(Exception e){
            
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        resultadocomando = new javax.swing.JTextArea();
        panelarrastrar = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        nombrecliente = new javax.swing.JLabel();
        comando = new javax.swing.JTextField();
        lupa = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        bgestados = new javax.swing.JPanel();
        memoria = new javax.swing.JPanel();
        labelmemoria = new javax.swing.JLabel();
        porcentajememoria = new javax.swing.JLabel();
        graficamemoria = new javax.swing.JLabel();
        disco = new javax.swing.JPanel();
        labeldisco = new javax.swing.JLabel();
        porcentajedisco = new javax.swing.JLabel();
        graficadisco = new javax.swing.JLabel();
        procesador = new javax.swing.JPanel();
        labelprocesador = new javax.swing.JLabel();
        porcentajeprocesador = new javax.swing.JLabel();
        graficaprocesador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        background.setBackground(new java.awt.Color(248, 248, 248));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(1, 1, 1));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        resultadocomando.setEditable(false);
        resultadocomando.setBackground(new java.awt.Color(251, 251, 251));
        resultadocomando.setColumns(22);
        resultadocomando.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        resultadocomando.setRows(5);
        resultadocomando.setBorder(null);
        scroll.setViewportView(resultadocomando);

        background.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 510, 460));

        panelarrastrar.setBackground(new java.awt.Color(215, 7, 81));
        panelarrastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelarrastrarMouseDragged(evt);
            }
        });
        panelarrastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelarrastrarMousePressed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closecolor.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelarrastrarLayout = new javax.swing.GroupLayout(panelarrastrar);
        panelarrastrar.setLayout(panelarrastrarLayout);
        panelarrastrarLayout.setHorizontalGroup(
            panelarrastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelarrastrarLayout.createSequentialGroup()
                .addGap(0, 748, Short.MAX_VALUE)
                .addComponent(close))
        );
        panelarrastrarLayout.setVerticalGroup(
            panelarrastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        background.add(panelarrastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));

        nombrecliente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        nombrecliente.setForeground(new java.awt.Color(1, 1, 1));
        nombrecliente.setText("Client@oper4323: ");
        background.add(nombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 30));

        comando.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comando.setText("Ingrese un comando");
        comando.setBorder(null);
        comando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comandoMousePressed(evt);
            }
        });
        comando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandoActionPerformed(evt);
            }
        });
        background.add(comando, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 330, 30));

        lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupacolor.png"))); // NOI18N
        lupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaMouseClicked(evt);
            }
        });
        background.add(lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        separador.setBackground(new java.awt.Color(1, 1, 1));
        separador.setForeground(new java.awt.Color(1, 1, 1));
        background.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 10));

        bgestados.setBackground(new java.awt.Color(215, 7, 81));

        memoria.setBackground(new java.awt.Color(254, 254, 254));

        labelmemoria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelmemoria.setText("Used Memory");

        graficamemoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barra-graficacolor.png"))); // NOI18N
        graficamemoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout memoriaLayout = new javax.swing.GroupLayout(memoria);
        memoria.setLayout(memoriaLayout);
        memoriaLayout.setHorizontalGroup(
            memoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoriaLayout.createSequentialGroup()
                .addGroup(memoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memoriaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(labelmemoria))
                    .addGroup(memoriaLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(graficamemoria)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memoriaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(porcentajememoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        memoriaLayout.setVerticalGroup(
            memoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoriaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelmemoria)
                .addGap(18, 18, 18)
                .addComponent(porcentajememoria, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(graficamemoria)
                .addGap(22, 22, 22))
        );

        disco.setBackground(new java.awt.Color(254, 254, 254));

        labeldisco.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labeldisco.setText("Used Disk");

        graficadisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barra-graficacolor.png"))); // NOI18N
        graficadisco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout discoLayout = new javax.swing.GroupLayout(disco);
        disco.setLayout(discoLayout);
        discoLayout.setHorizontalGroup(
            discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discoLayout.createSequentialGroup()
                .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discoLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(labeldisco))
                    .addGroup(discoLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(graficadisco))
                    .addGroup(discoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(porcentajedisco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        discoLayout.setVerticalGroup(
            discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labeldisco)
                .addGap(18, 18, 18)
                .addComponent(porcentajedisco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(graficadisco)
                .addGap(22, 22, 22))
        );

        procesador.setBackground(new java.awt.Color(254, 254, 254));

        labelprocesador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelprocesador.setText("Used Processor");

        graficaprocesador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barra-graficacolor.png"))); // NOI18N
        graficaprocesador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout procesadorLayout = new javax.swing.GroupLayout(procesador);
        procesador.setLayout(procesadorLayout);
        procesadorLayout.setHorizontalGroup(
            procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, procesadorLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(labelprocesador)
                .addGap(46, 46, 46))
            .addGroup(procesadorLayout.createSequentialGroup()
                .addGroup(procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(procesadorLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(graficaprocesador))
                    .addGroup(procesadorLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(porcentajeprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        procesadorLayout.setVerticalGroup(
            procesadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(procesadorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelprocesador)
                .addGap(18, 18, 18)
                .addComponent(porcentajeprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(graficaprocesador)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout bgestadosLayout = new javax.swing.GroupLayout(bgestados);
        bgestados.setLayout(bgestadosLayout);
        bgestadosLayout.setHorizontalGroup(
            bgestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgestadosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bgestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        bgestadosLayout.setVerticalGroup(
            bgestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgestadosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(memoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(procesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        background.add(bgestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 250, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientela.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandoActionPerformed
        
    }//GEN-LAST:event_comandoActionPerformed

    private void panelarrastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelarrastrarMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panelarrastrarMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
    }//GEN-LAST:event_formMouseDragged

    private void panelarrastrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelarrastrarMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panelarrastrarMouseDragged

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void comandoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comandoMousePressed
        if(comando.getText().equals("Ingrese un comando")){
            comando.setText("");
        }
    }//GEN-LAST:event_comandoMousePressed

    private void lupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaMouseClicked
        
        //resultado de codigo
       
       String comandoMostrar=c.comando(comando.getText(),"-.-0");
       
       System.out.println(comandoMostrar);
       if(comando.getText().equals("clear")){
           resultadocomando.setText("");
       }else {
           //resultadocomando.append(comandoMostrar);
           resultadocomando.setText(resultadocomando.getText()+comandoMostrar);
       }
       comando.setText("");
        
    }//GEN-LAST:event_lupaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel bgestados;
    private javax.swing.JLabel close;
    private javax.swing.JTextField comando;
    private javax.swing.JPanel disco;
    private javax.swing.JLabel graficadisco;
    private javax.swing.JLabel graficamemoria;
    private javax.swing.JLabel graficaprocesador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labeldisco;
    private javax.swing.JLabel labelmemoria;
    private javax.swing.JLabel labelprocesador;
    private javax.swing.JLabel lupa;
    private javax.swing.JPanel memoria;
    private javax.swing.JLabel nombrecliente;
    private javax.swing.JPanel panelarrastrar;
    private javax.swing.JLabel porcentajedisco;
    private javax.swing.JLabel porcentajememoria;
    private javax.swing.JLabel porcentajeprocesador;
    private javax.swing.JPanel procesador;
    private javax.swing.JTextArea resultadocomando;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
